
server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 2KB
    mime-types: video/mpeg4-generic, video/mpeg, video/mp4, video/ogg, video/3gpp, video/x-matroska
    ffmpeg: ${FFMPEG_PATH:ffmpeg}
    ffprobe: ${FFPROBE_PATH:ffprobe}
spring:
  application:
    name: youtube
  datasource:
    url: jdbc:postgresql://localhost:5454/youtube
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        open-in-view: false
        properties:
          hibernate:
            format_sql: false
            dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
            connection:
              pool_size: 20
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    baselineOnMigrate: true
    enabled: true
    locations: classpath:db/migration
    placeholderReplacement: true

  servlet:
    multipart:
      enabled: true
      max-request-size: 200MB
      max-file-size: 200MB
  mvc:
    dispatch-options-request: true
